version: "3.8"

services:
  app:
    build:
      context: .
    container_name: myapi_app
    restart: always
    expose:
      - "8000"  # Внутренний порт для FastAPI
    volumes:
      - .:/app  # Прокидываем проект внутрь контейнера
    command: python main.py  # Просто запускаем main.py

  nginx:
    image: nginx:latest
    container_name: myapi_nginx
    restart: always
    ports:
      - "80:80"  # Внешний порт
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
